### ISSUE TITLE
Undefined array key on empty log

### ISSUE THREAD

**Issue by malohtie** [opcodesio/log-viewer#148]
hello
i  came across this bug when error log is empty like below

```
[2022-11-07 17:51:33] production.ERROR: 
```

```php
production.ERROR: Undefined array key 1 {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined array key 1 at /var/app/vendor/opcodesio/log-viewer/src/Log.php:52)


[stacktrace]
#0 /var/app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/app/vendor/opcodesio/log-viewer/src/Log.php(52): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/app/vendor/opcodesio/log-viewer/src/LogReader.php(521): Opcodes\\LogViewer\\Log->__construct()
#3 /var/app/vendor/opcodesio/log-viewer/src/LogReader.php(472): Opcodes\\LogViewer\\LogReader->makeLog()
#4 /var/app/vendor/opcodesio/log-viewer/src/LogReader.php(431): Opcodes\\LogViewer\\LogReader->next()
#5 /var/app/vendor/opcodesio/log-viewer/src/LogReader.php(512): Opcodes\\LogViewer\\LogReader->get()
#6 /var/app/vendor/opcodesio/log-viewer/src/Http/Livewire/LogList.php(97): Opcodes\\LogViewer\\LogReader->paginate()
....
"} 
```

**Comment by arukompas** [comment]
Hey @malohtie , thanks for the report! Fixed in `v1.6.5`
